### ISSUE TITLE
Poetry downgrade breaking Python on p3.9/n12

### ISSUE THREAD

**Issue by ericboucher** [nikolaik/docker-python-nodejs#36] opened 2021-10-18 02:01 UTC
Hi @nikolaik!

First, thanks a lot for creating this super useful docker!
We use it in our CI and for some reason, it started failing since the last image update with the following error:

`python: error while loading shared libraries: libpython3.9.so.1.0: cannot open shared object file: No such file or directory`

We did not see any apparent changes in your latest image so we are a bit confused as too what might be happening...

Steps to reproduce:

Run `docker run --rm -it --entrypoint bash nikolaik/python-nodejs:python3.9-nodejs12`
Run `python` -> the error appears.

cc @laurentS

**Comment by nikolaik** [comment] 2022-09-25 18:50
I'll close this for now, even though we never got to the root cause of your issue.

**Closed by nikolaik** 2022-09-25 18:50 UTC
